# Generated by Django 5.1.6 on 2025-02-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_entry_creationdate_alter_entry_entrydate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='wasConsolidated',
            field=models.BooleanField(default=False),
        ),
    ]
