# Generated by Django 5.1.6 on 2025-02-08 14:39

import users.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='taxNumber',
            field=models.CharField(max_length=14, unique=True, validators=[users.validator.isTaxNumberValid]),
        ),
    ]
